import { stringify } from 'yaml'
import type { EntryType } from '../../contract.js'
import type { Program } from '../../ir.js'
import { canEmit } from '../capability.js'

export type BouncerOptions = {
  mode?: 'observe' | 'guard' | 'full'
  tools?: string[]
  timeoutMs?: number
}

const cmp = (op: 'gte' | 'lte', v: number) => `${op === 'gte' ? '>=' : '<='}${v}`

// bouncer reads criteria.true/false as STRINGS. EntryType may be an object, and
// String({}) renders "[object Object]" silently — JSON.stringify keeps the content.
const asString = (v: EntryType | undefined): string =>
  v == null ? '' : typeof v === 'string' ? v : JSON.stringify(v)

export function emitBouncerPolicy(p: Program, opts: BouncerOptions = {}): string {
  const issues = canEmit(p, 'bouncer').filter(i => i.severity === 'error')
  if (issues.length) {
    throw new Error(`Cannot emit a bouncer policy:\n${issues.map(i => `  ${i.path}: ${i.message}`).join('\n')}`)
  }
  for (const d of p.decisions) {
    if (d.id === 'any') throw new Error('"any" is reserved by bouncer as the cross-question selector.')
  }

  const questions: Record<string, unknown> = {}
  for (const d of p.decisions) {
    const c = d.criteria && !Array.isArray(d.criteria)
      ? (d.criteria as { true?: EntryType; false?: EntryType }) : undefined
    // No `type` key: bouncer hardcodes type "noul" for every question.
    // Only the keys `true` and `false` are read; anything else is silently dropped.
    questions[d.id] = c
      ? { instructions: asString(d.instructions), criteria: { true: asString(c.true), false: asString(c.false) } }
      : { instructions: asString(d.instructions) }
  }

  const rules: unknown[] = p.reduce.rules.map(r => {
    const c = r.when[0]   // canEmit guarantees exactly one
    if (c.op === 'is' || c.op === 'uncertain') {
      // Folding a richer condition into one question's text is the collapsed-verdict
      // shape the measurements rule out (0.42/0.35/0.23 at confidence 0.13). Refuse.
      throw new Error(`bouncer rules compare a noul probability; "${c.op}" cannot be expressed.`)
    }
    return { when: { [c.id]: { p: cmp(c.op, c.value) } }, then: r.then }
  })
  rules.push({ default: p.reduce.otherwise })   // exactly one terminal default, last

  const doc = stringify({
    version: 1,
    backend: 'jev',
    mode: opts.mode ?? 'observe',
    timeout_ms: opts.timeoutMs ?? 800,
    on_error: 'passthrough',
    gate: { tools: opts.tools ?? ['Bash', 'Edit', 'Write', 'NotebookEdit'], questions, rules },
  })

  const provenance = p.decisions
    .filter(d => d.source)
    .map(d => `# ${d.id}: ${d.source!.file}:${d.source!.line} — ${d.source!.quote.replace(/\r\n|\r|\n/g, ' ')}`)
    .join('\n')

  // residual has no field in the schema and unknown keys are ignored silently, so a
  // comment is the only honest place for it.
  // Split on every line ending, not just \n: YAML ends a comment at a lone CR too, so a
  // residual carrying CRLF or CR (it is prose lifted from a human document) would put its
  // remaining text into the document body, where it parses as policy.
  const residual = p.residual
    ? `#\n# STILL REQUIRES A GENERATIVE MODEL — not enforced by this policy:\n${
        p.residual.split(/\r\n|\r|\n/g).map(l => `# ${l}`).join('\n')}\n` : ''

  return `# Generated by jevc from natural-language rules.
# Review the questions and thresholds — they are the part humans must check.
# Ships in observe mode: it logs and emits nothing. Run \`bouncer calibrate\`
# against your own traffic before moving to guard.
#
# State is built by bouncer, not by jevc: word instructions against its fixed
# vocabulary (tool, action.kind, inside_project, outside_location, sensitive).
${provenance ? `#\n${provenance}\n` : ''}${residual}
${doc}`
}
