import { stringify } from 'yaml'
import type { EntryType } from '../../contract.js'
import type { Program } from '../../ir.js'
import { canEmit, toolgateThresholds } from '../capability.js'

const asString = (v: EntryType | undefined): string =>
  v == null ? '' : typeof v === 'string' ? v : JSON.stringify(v)

export function emitToolgatePolicy(p: Program): string {
  // Every refusal — the reserved off_task id, the threshold algebra, all of it — lives in
  // canEmit now. While toolgateThresholds sat here, canEmit returned [] for a dozen
  // programs this function then threw on, and canEmit is the gate a consumer branches on.
  const issues = canEmit(p, 'toolgate').filter(i => i.severity === 'error')
  if (issues.length) {
    throw new Error(`Cannot emit a toolgate policy:\n${issues.map(i => `  ${i.path}: ${i.message}`).join('\n')}`)
  }
  // canEmit reported this function's issues, so the thresholds are here. Checked anyway:
  // `thresholds: null` in the file loads fine and runs at toolgate's own 0.85/0.55.
  const { thresholds } = toolgateThresholds(p)
  if (!thresholds) throw new Error('Cannot emit a toolgate policy: the reducer has no deny/ask thresholds.')

  // Null-prototype: `questions['__proto__'] = ...` on a plain object literal hits
  // Object.prototype's setter and re-parents the map instead of adding a key. The policy
  // still loads — max() simply runs over one question fewer — so the gate weakens with
  // nothing to show for it. The id is live input: from-schema.ts uses the JSON Schema
  // property name verbatim.
  const questions: Record<string, unknown> = Object.create(null)
  for (const d of p.decisions) {
    const c = d.criteria && !Array.isArray(d.criteria)
      ? (d.criteria as { true?: EntryType; false?: EntryType }) : undefined
    // A side the Program does not describe is omitted, not sent as "": criteria goes
    // into the model's prompt, where an empty string says the side is described by
    // nothing rather than saying nothing about it.
    const criteria: Record<string, string> = {}
    if (c?.true != null) criteria.true = asString(c.true)
    if (c?.false != null) criteria.false = asString(c.false)
    // validatePolicy throws unless type is exactly "boolean". Overriding a built-in id is
    // a wholesale per-key replace, not a deep merge, so criteria must be re-emitted here.
    questions[d.id] = Object.keys(criteria).length
      ? { type: 'boolean', instructions: asString(d.instructions), criteria }
      : { type: 'boolean', instructions: asString(d.instructions) }
  }

  // The belt to the null-prototype brace: a question that never reaches the file is
  // invisible by construction here, because max() over the survivors still answers.
  const lost = p.decisions.filter(d => !Object.hasOwn(questions, d.id)).map(d => d.id)
  if (lost.length) {
    throw new Error(`Refusing to emit a toolgate policy missing question(s) ${lost.join(', ')}: the policy would load and return verdicts from the questions that survived.`)
  }

  // Split on every line ending, not just \n: YAML ends a comment at a lone CR too, so a
  // residual carrying CRLF or CR (it is prose lifted from a human document) would put its
  // remaining text into the document body, where it parses as policy.
  const residual = p.residual
    ? `#\n# STILL REQUIRES A GENERATIVE MODEL — not enforced by this policy:\n${
        p.residual.split(/\r\n|\r|\n/g).map(l => `# ${l}`).join('\n')}\n` : ''

  return `# Generated by jevc.
# There is deliberately no per-project discovery: point TOOLGATE_POLICY at this
# file rather than clobbering ~/.toolgate/toolgate.yaml.
#
# toolgate merges these over its four built-in questions (destructive,
# exfiltration, privilege, off_task). Built-in questions cannot be removed —
# reuse a built-in id to shadow one. Every question must be type: boolean;
# choice and score decisions cannot be lowered to this target.
#
# The verdict is max(probability) over ALL questions — the built-ins included —
# against the two thresholds below. Every question is therefore implicitly OR'd
# at the same severity: adding one can only make the gate stricter.
${residual}
${stringify({ questions, thresholds })}`
}
