import { stringify } from 'yaml'
import type { EntryType } from '../../contract.js'
import type { Program } from '../../ir.js'
import { canEmit } from '../capability.js'

/** Dropped when no task context exists (engine.ts:63), so a custom one would vanish. */
const RESERVED = 'off_task'

const asString = (v: EntryType | undefined): string =>
  v == null ? '' : typeof v === 'string' ? v : JSON.stringify(v)

/**
 * toolgate's reducer is not per-question thresholds. It takes the MAX probability over
 * every question, then `>= deny` => deny, `>= ask` => ask, else allow — two scalars, and
 * that is the entire tunable surface. Emitting a per-question threshold map produces YAML
 * toolgate accepts and ignores, leaving deny/ask at their 0.85/0.55 defaults: a policy
 * that loads cleanly and means something else. So the reducer is lowered only when it is
 * genuinely max-then-two-thresholds shaped, and refused otherwise.
 */
function refuse(why: string): never {
  throw new Error(
    `Cannot emit a toolgate policy: ${why}\n` +
    `  toolgate reduces by max(probability) over all questions, then two scalars ` +
    `(deny, ask). Express the reducer as one shared deny threshold and one shared ask ` +
    `threshold over every question, or emit to a code target.`)
}

function thresholdsFor(p: Program): { deny: number; ask: number } {
  if (p.reduce.otherwise !== 'allow') refuse(`the fallthrough is "${p.reduce.otherwise}"; toolgate's is always allow.`)

  const byVerdict = new Map<string, Set<number>>()
  const covered = new Map<string, Set<string>>()   // verdict -> question ids
  for (const r of p.reduce.rules) {
    if (r.then !== 'deny' && r.then !== 'ask') refuse(`rule verdict "${r.then}" is not deny or ask.`)
    for (const c of r.when) {
      if (c.op !== 'gte') refuse(`condition op "${c.op}" on "${c.id}"; only >= maps to a threshold.`)
      byVerdict.set(r.then, (byVerdict.get(r.then) ?? new Set()).add(c.value))
      covered.set(r.then, (covered.get(r.then) ?? new Set()).add(c.id))
    }
  }

  for (const verdict of ['deny', 'ask']) {
    const vals = byVerdict.get(verdict)
    if (!vals) refuse(`no ${verdict} rule; toolgate always applies both thresholds.`)
    if (vals!.size > 1) refuse(`${verdict} uses ${vals!.size} different thresholds (${[...vals!].join(', ')}); max-over-questions can only apply one.`)
    const ids = covered.get(verdict)!
    const missing = p.decisions.filter(d => !ids.has(d.id)).map(d => d.id)
    // Max-over-questions means an uncovered question still feeds the same threshold —
    // stricter than the Program says. Silent tightening is still silent divergence.
    if (missing.length) refuse(`questions ${missing.join(', ')} have no ${verdict} rule, but max-over-questions applies the ${verdict} threshold to them anyway.`)
  }

  const deny = [...byVerdict.get('deny')!][0]
  const ask = [...byVerdict.get('ask')!][0]
  // validatePolicy enforces 0 <= ask <= deny <= 1.
  if (!(ask <= deny)) refuse(`ask (${ask}) is above deny (${deny}); validatePolicy requires ask <= deny.`)
  return { deny, ask }
}

export function emitToolgatePolicy(p: Program): string {
  const issues = canEmit(p, 'toolgate').filter(i => i.severity === 'error')
  if (issues.length) {
    throw new Error(`Cannot emit a toolgate policy:\n${issues.map(i => `  ${i.path}: ${i.message}`).join('\n')}`)
  }
  for (const d of p.decisions) {
    if (d.id === RESERVED) {
      throw new Error(`"${RESERVED}" is dropped by toolgate when there is no task context; pick another id.`)
    }
  }

  const questions: Record<string, unknown> = {}
  for (const d of p.decisions) {
    const c = d.criteria && !Array.isArray(d.criteria)
      ? (d.criteria as { true?: EntryType; false?: EntryType }) : undefined
    // validatePolicy throws unless type is exactly "boolean". Overriding a built-in id is
    // a wholesale per-key replace, not a deep merge, so criteria must be re-emitted here.
    questions[d.id] = c
      ? { type: 'boolean', instructions: asString(d.instructions),
          criteria: { true: asString(c.true), false: asString(c.false) } }
      : { type: 'boolean', instructions: asString(d.instructions) }
  }

  // Split on every line ending, not just \n: YAML ends a comment at a lone CR too, so a
  // residual carrying CRLF or CR (it is prose lifted from a human document) would put its
  // remaining text into the document body, where it parses as policy.
  const residual = p.residual
    ? `#\n# STILL REQUIRES A GENERATIVE MODEL — not enforced by this policy:\n${
        p.residual.split(/\r\n|\r|\n/g).map(l => `# ${l}`).join('\n')}\n` : ''

  return `# Generated by jevc.
# There is deliberately no per-project discovery: point TOOLGATE_POLICY at this
# file rather than clobbering ~/.toolgate/toolgate.yaml.
#
# toolgate merges these over its four built-in questions (destructive,
# exfiltration, privilege, off_task). Built-in questions cannot be removed —
# reuse a built-in id to shadow one. Every question must be type: boolean;
# choice and score decisions cannot be lowered to this target.
#
# The verdict is max(probability) over ALL questions — the built-ins included —
# against the two thresholds below. Every question is therefore implicitly OR'd
# at the same severity: adding one can only make the gate stricter.
${residual}
${stringify({ questions, thresholds: thresholdsFor(p) })}`
}
