import type { EntryType } from '../contract.js'
import { uncertaintyOf } from '../ir.js'
import type { Decision, Program } from '../ir.js'
// One definition, shared with native.ts: `idKey` and the line-terminator set were
// byte-identical copies here and there, and nothing forced them to stay in step. The
// module is named for the TYPESCRIPT targets — its ECMAScript terminator set is
// deliberately NOT the one bouncer.ts, toolgate.ts and langchain.ts use, and the header
// of ts-lowering.ts says why all three must stay separate.
import { tsIdKey as idKey, tsValue, TS_LINE_TERMINATORS as LINE } from './ts-lowering.js'

// `tsValue`, never a bare `JSON.stringify`, at every VALUE splice here and in the LEGEND
// map below — five sites, all of them in expression position, where a nested `__proto__`
// key is the prototype setter and the entry disappears from the emitted object. See
// ts-lowering.ts; native.ts has the same four, and LEGEND is this emitter's fifth.
function question(d: Decision): string {
  if (d.kind === 'noul') {
    // EvaluationModelV4 renames noul -> boolean; the answer field becomes `probability`.
    const c = d.criteria && !Array.isArray(d.criteria) ? `, criteria: ${tsValue(d.criteria)}` : ''
    return `  ${idKey(d.id)}: { type: 'boolean', instructions: ${tsValue(d.instructions)}${c} },`
  }
  if (d.kind === 'score') {
    const lv = (d.criteria as readonly EntryType[]).map(c => tsValue(c)).join(', ')
    // `as const` is load-bearing: without it the level type degrades to `number`.
    return `  ${idKey(d.id)}: { type: 'score', instructions: ${tsValue(d.instructions)}, criteria: [${lv}] as const },`
  }
  const opts = Object.entries(d.criteria as Record<string, EntryType>)
    .map(([k, v]) => `${idKey(k)}: ${tsValue(v)}`).join(', ')
  return `  ${idKey(d.id)}: { type: 'choice', instructions: ${tsValue(d.instructions)}, criteria: { ${opts} } as const },`
}

export function emitAiSdk(p: Program, name = 'program'): string {
  // The fifth `__proto__` value site, and the one no previous round reached: LEGEND is a
  // SECOND copy of every score level, so a level description carrying its own `__proto__`
  // key was dropped here as well as from the questions map — leaving the legend and the
  // wire disagreeing about what level 0 means. The keys are "0", "1", ... and can never be
  // `__proto__`, so only the value needs `tsValue`.
  const legends = p.decisions
    .filter(d => d.kind === 'score')
    .map(d => `  ${idKey(d.id)}: { ${(d.criteria as readonly EntryType[])
      .map((c, i) => `${JSON.stringify(String(i))}: ${tsValue(c)}`).join(', ')} },`)
    .join('\n')

  // Each decision's uncertainty rule, RESOLVED from the Program (uncertaintyOf supplies
  // jevc's defaults where a decision declares none) and carried into the generated module.
  // The emitter used to lower every `uncertain` condition to a literal `< 0.5`, which is a
  // different question from the one the Program asks.
  const uncertainties = p.decisions.map(d => {
    const u = uncertaintyOf(d)
    const body = 'band' in u
      ? `{ band: [${u.band[0]}, ${u.band[1]}] }`
      : `{ belowConfidence: ${u.belowConfidence} }`
    return `  ${idKey(d.id)}: ${body},`
  }).join('\n')

  const rules = p.reduce.rules.map((r, i) => {
    // Which rule could not be evaluated, carried into the call. The evidence helpers below
    // THROW on an unanswered question, and a throw out of a generated module is worthless
    // without it: the stack names `compare`, the Program names `rule 3`, and nothing in the
    // artifact connects the two. First-match-wins makes the index meaningful on its own, and
    // the verdict makes it readable without counting lines.
    const where = JSON.stringify(`rule ${i} -> ${r.then}`)
    const conds = r.when.map(c => {
      const at = `a[${JSON.stringify(c.id)}]`
      if (c.op === 'is') return `${at}?.choice === ${JSON.stringify(c.value)}`
      if (c.op === 'uncertain') return `uncertain(a, ${JSON.stringify(c.id)}, confidence, ${where})`
      return `compare(a, ${JSON.stringify(c.id)}, confidence, ${c.op === 'gte' ? '">="' : '"<="'}, ${c.value}, ${where})`
    }).join(' && ')
    // `when: []` is an empty conjunction and `[].every(...)` is true, so the rule fires
    // unconditionally — `true` is what that means here, and joining nothing produced the
    // unparseable `if ()`.
    return `  if (${conds || 'true'}) return ${JSON.stringify(r.then)}`
  }).join('\n')

  return `// Generated by jevc for @ai-sdk/typesafe-ai.
// NOTE: this backend renames noul -> boolean and its answer field -> probability,
// drops \`legend\` entirely, and returns confidence only under providerMetadata,
// where it may be ABSENT. Values are rounded to 2dp, so distributions may not sum to 1.
import { createTypeSafeAi } from '@ai-sdk/typesafe-ai'

// The target drops legend, so jevc keeps it here. A bare score is uninterpretable without it.
export const LEGEND = {
${legends || '  // no score questions'}
} as const

export const ${name}Questions = {
${p.decisions.map(question).join('\n')}
} as const

/** Every decision's uncertainty rule as the Program declares it: a band around the
 *  boundary for a boolean, a confidence floor for a choice or score. */
export const UNCERTAINTY: Record<string, { band?: [number, number]; belowConfidence?: number }> = {
${uncertainties || '  // no decisions'}
}

/**
 * Confidence is not returned inline on this backend — it is relocated to
 * result.providerMetadata.typesafe.confidence, keyed by question id, and is ABSENT (not
 * null) when the wire returned none. Pass that map in: it is the model's own number,
 * whereas the fallback recomputes from probabilities that the backend rounds to 2dp, so
 * the two disagree near a threshold. Absence still never means zero.
 */
export function confidenceFrom(
  answer: { probabilities?: Record<string, number>; probability?: number } | undefined,
  provided?: number,
): number {
  if (typeof provided === 'number') return provided
  if (typeof answer?.probability === 'number') return Math.abs(2 * answer.probability - 1)
  const ps = Object.values(answer?.probabilities ?? {})
  if (!ps.length) return 0
  const sorted = [...ps].sort((x, y) => y - x)
  return sorted[0] - (sorted[1] ?? 0)
}

/**
 * The number a threshold compares against, chosen the way jevc's own runtime chooses it:
 * a boolean's probability, a score's level index, otherwise (a choice) its confidence.
 * probability and score live under different keys on this backend, and a choice answer
 * has neither — reading 0 there made every gte false and every lte true regardless of
 * what the model returned. Refusing choice thresholds in canEmit was the alternative,
 * rejected because this target takes an arbitrary reducer: the Program is expressible
 * here, so the emitter should express it rather than narrow the target.
 */
function valueOf(a: Record<string, any>, id: string, confidence: Record<string, number>): number | undefined {
  const ans = a[id]
  if (!ans) return undefined
  return ans.probability ?? ans.score ?? confidenceFrom(ans, confidence[id])
}

/**
 * A rule whose question was not answered REFUSES TO PRODUCE A VERDICT — the same answer
 * jevc's own reducer gives (\`value\`/\`isUncertain\` in src/runtime.ts both throw), and
 * therefore the same answer the \`sdk\` target gives, since that one calls straight into it.
 *
 * This used to return \`false\` — "the rule does not fire" — citing bouncer, which skips a
 * question it has no answer for. That reasoning is sound FOR BOUNCER and unsound here.
 * Bouncer is a YAML policy document: it has no exceptions, so skipping is the only thing
 * left to it, and target-bouncer.md says so. TypeScript has exceptions. The citation was to
 * a constraint that does not bind this target, and what it bought was a fail-open: \`false\`
 * on a DENY rule is the deny quietly not firing, so an incomplete answer map falls through
 * to \`otherwise\`, which in every gate anyone writes is the permissive verdict. Measured,
 * on one Program with the \`gte\` question unanswered: runReducer \`THROW\`, sdk \`THROW\`,
 * ai-sdk \`allow\`, langchain \`allow\`. Two of the four evaluators of one Program returned
 * the most permissive verdict in the list and two refused. That disagreement is the bug,
 * and this is the direction that keeps the one implementation that was already right.
 *
 * \`is\` is the exception, in every target: \`choiceOf\` returns undefined for an unanswered
 * question and never throws (src/runtime.ts), so \`a[id]?.choice === "x"\` is correctly
 * false. "Nobody answered" and "the answer was not that option" are the same fact for \`is\`
 * and different facts for a threshold.
 *
 * KNOWN TARGET LIMITATION, stated here so it is not rediscovered: \`--emit bouncer\` and
 * \`--emit toolgate\` still skip, and cannot do otherwise. A consumer who needs the four
 * code targets' refusal semantics out of a policy target has to check the answer set is
 * complete before the gate runs; the policy document itself cannot.
 */
const noAnswer = (id: string, rule: string): Error =>
  new Error(\`No answer for decision "\${id}", read by \${rule}. Refusing to compute a verdict: an unanswered question treated as "the condition did not hold" makes a deny rule silently not fire and the reducer fall through to "otherwise". jevc's own runReducer throws here too.\`)

function compare(a: Record<string, any>, id: string, confidence: Record<string, number>,
                 op: '>=' | '<=', threshold: number, rule: string): boolean {
  const v = valueOf(a, id, confidence)
  if (v === undefined) throw noAnswer(id, rule)
  return op === '>=' ? v >= threshold : v <= threshold
}

/** Uncertainty per UNCERTAINTY above, not a fixed 0.5. A boolean's band is tested on its
 *  probability; everything else against its confidence. An absent answer is not certain
 *  either — see \`noAnswer\`: there is no measurement, so there is no verdict. */
function uncertain(a: Record<string, any>, id: string, confidence: Record<string, number>, rule: string): boolean {
  const ans = a[id]
  if (!ans) throw noAnswer(id, rule)
  // Object.hasOwn, not a bare \`UNCERTAINTY[id]\` truthiness test. A plain object answers
  // \`constructor\`, \`toString\` and the rest of Object.prototype with a truthy value, so the
  // old \`if (!rule)\` guard passed for an id the program never declared and the comparison
  // ran against \`undefined\` — false, silently, which switched the escalate-to-human rule
  // off. runReducer looks the decision up with \`p.decisions.find\`, which has no prototype
  // chain to fall through; this is how a map says the same thing.
  if (!Object.hasOwn(UNCERTAINTY, id)) {
    throw new Error(\`No decision "\${id}" in this program, but \${rule} asks whether it is uncertain. Refusing to compute a verdict from a rule whose question does not exist.\`)
  }
  const u = UNCERTAINTY[id]
  if (u.band) return ans.probability > u.band[0] && ans.probability < u.band[1]
  return confidenceFrom(ans, confidence[id]) < u.belowConfidence!
}

/**
 * result.providerMetadata.typesafe.confidence, narrowed. The field is statically
 * JSONObject, so reaching it by hand does not typecheck — this is the guard jevc has to
 * supply rather than make every caller write a cast. An ABSENT entry means "the wire
 * returned no confidence for this question, recompute it from the distribution", which
 * is why non-numbers are dropped instead of coerced: absence must never read as 0.
 *
 *   const result  = await experimental_evaluate({ model, state, questions: programQuestions })
 *   const verdict = reduce(result.answers, confidenceOf(result))
 */
export function confidenceOf(result: { providerMetadata?: Record<string, unknown> } | undefined): Record<string, number> {
  const typesafe = result?.providerMetadata?.['typesafe'] as { confidence?: unknown } | undefined
  const c = typesafe?.confidence
  if (!c || typeof c !== 'object') return {}
  return Object.fromEntries(
    Object.entries(c as Record<string, unknown>).filter(([, v]) => typeof v === 'number'),
  ) as Record<string, number>
}

/** The verdict is computed here, in code — never asked of the model.
 *  \`confidence\` is required on purpose. It used to default to \`{}\`, which made
 *  \`reduce(result.answers)\` — the short call, the one that compiles — evaluate every
 *  choice/score threshold and every belowConfidence rule against confidenceFrom's
 *  top-minus-second MARGIN instead of the model's own confidence. Those are different
 *  statistics, not approximations of each other: on the backend's own verified answer
 *  {allow 0.42, block 0.35, ask 0.23} the margin is 0.07 and the reported confidence is
 *  0.13, which lands on opposite sides of a 0.10 threshold. Recomputation is the
 *  documented fallback for a question the wire returned no confidence for — per-question,
 *  inside confidenceFrom — never the default for all of them. */
export function reduce(a: Record<string, any>, confidence: Record<string, number>): string {
${rules}
  return ${JSON.stringify(p.reduce.otherwise)}
}

// This backend reads TYPESAFE_AI_API_KEY; langchain-typesafe and jevc's own .env read
// TYPESAFE_API_KEY. Accept either, or an environment set up for jevc throws
// AI_LoadAPIKeyError here.
export const model = createTypeSafeAi({ apiKey: process.env.TYPESAFE_AI_API_KEY ?? process.env.TYPESAFE_API_KEY })
  .evaluationModel('jev-latest')
${p.residual ? `\n${['Still requires a generative model:', ...p.residual.split(LINE)]
    .map(l => `// ${l}`).join('\n')}\n` : ''}`
}
