import type { EntryType, JsonValue } from '../contract.js'
import { uncertaintyOf } from '../ir.js'
import type { Decision, Program } from '../ir.js'

/**
 * A Python literal for an EntryType. JSON.stringify is not enough here: JSON's
 * true/false/null are not Python, and String(v) on an object renders
 * "[object Object]". JSON string escapes ARE a subset of Python's, so strings
 * pass through JSON.stringify unchanged.
 */
function py(v: JsonValue | undefined): string {
  if (v === undefined || v === null) return 'None'
  if (typeof v === 'string') return JSON.stringify(v)
  if (typeof v === 'boolean') return v ? 'True' : 'False'
  if (typeof v === 'number') return Number.isFinite(v) ? String(v) : 'None'
  if (Array.isArray(v)) return `[${v.map(py).join(', ')}]`
  return `{${Object.entries(v).map(([k, x]) => `${JSON.stringify(k)}: ${py(x)}`).join(', ')}}`
}

function question(d: Decision): string {
  if (d.kind === 'noul') {
    const c = d.criteria && !Array.isArray(d.criteria)
      ? (d.criteria as { true?: EntryType; false?: EntryType }) : undefined
    // criteria is passed explicitly: the library's own default is unreachable dead code.
    const crit = c ? `, criteria=NoulCriteria(true=${py(c.true ?? null)}, false=${py(c.false ?? null)})` : ''
    return `    ${py(d.id)}: Noul(instructions=${py(d.instructions)}${crit}),`
  }
  if (d.kind === 'score') {
    const lv = (d.criteria as readonly EntryType[]).map(py).join(', ')
    return `    ${py(d.id)}: Score(instructions=${py(d.instructions)}, criteria=[${lv}]),`
  }
  const opts = Object.entries(d.criteria as Record<string, EntryType>)
    .map(([k, v]) => `${py(k)}: ${py(v)}`).join(', ')
  return `    ${py(d.id)}: Choice(instructions=${py(d.instructions)}, criteria={${opts}}),`
}

export function emitLangchain(p: Program, name = 'program'): string {
  // Each decision's uncertainty rule, RESOLVED from the Program (uncertaintyOf supplies
  // jevc's defaults where a decision declares none) rather than assumed to be 0.5.
  const uncertainties = p.decisions.map(d => {
    const u = uncertaintyOf(d)
    const body = 'band' in u
      ? `{"band": [${py(u.band[0])}, ${py(u.band[1])}]}`
      : `{"below_confidence": ${py(u.belowConfidence)}}`
    return `    ${py(d.id)}: ${body},`
  }).join('\n')

  const rules = p.reduce.rules.map(r => {
    const conds = r.when.map(c => {
      if (c.op === 'is') return `answers[${py(c.id)}].choice == ${py(c.value)}`
      if (c.op === 'uncertain') return `_uncertain(answers, ${py(c.id)})`
      // py(), not interpolation: Infinity and NaN are JS globals and Python NameErrors,
      // and nothing upstream rejects a non-finite threshold.
      return `_compare(answers, ${py(c.id)}, ${py(c.op === 'gte' ? '>=' : '<=')}, ${py(c.value)})`
    }).join(' and ')
    // `when: []` is an empty conjunction and `[].every(...)` is true, so the rule fires
    // unconditionally — `True` is what that means here, and joining nothing produced the
    // unparseable `if :`.
    return `    if ${conds || 'True'}:\n        return ${py(r.then)}`
  }).join('\n')

  return `# Generated by jevc for langchain-typesafe.
# api_key and base_url come from the environment: TypeSafeClassifier sets
# extra="forbid", so a stray kwarg is a hard error.
from langchain_typesafe import Choice, Noul, NoulCriteria, Score, TypeSafeClassifier

${name}_questions = {
${p.decisions.map(question).join('\n')}
}

classifier = TypeSafeClassifier(questions=${name}_questions, model="jev-latest")

# Each decision's uncertainty rule as the Program declares it. A noul answer is
# {type, noul} with no .confidence field at all, so its band is tested on .noul; a choice
# or score answer carries a required .confidence, which its floor is tested against.
_UNCERTAINTY = {
${uncertainties}
}


def _value(answers, qid):
    """The number a threshold compares against, as jevc's own runtime picks it: a noul's
    value, a score's level index, otherwise a choice's confidence. A choice answer has
    neither .noul nor .score, and falling back to 0 there made every >= fail and every
    <= pass whatever the model said. Nested getattr with a None sentinel, not "or": a
    legitimate noul of 0.0 is falsy and would fall through."""
    ans = answers.get(qid)
    if ans is None:
        return None
    noul = getattr(ans, "noul", None)
    if noul is not None:
        return noul
    score = getattr(ans, "score", None)
    if score is not None:
        return score
    return getattr(ans, "confidence", None)


def _compare(answers, qid, op, threshold) -> bool:
    """A rule whose question was not answered does not fire, in either direction: absence
    of evidence is not evidence, and it is bouncer's rule for the same situation. An
    unanswered question read as 0 satisfies every upper bound, which turns "we never
    asked" into a confident no."""
    v = _value(answers, qid)
    if v is None:
        return False
    return v >= threshold if op == ">=" else v <= threshold


def _uncertain(answers, qid) -> bool:
    rule = _UNCERTAINTY.get(qid)
    ans = answers.get(qid)
    # No answer means nothing was measured, which is not the same as being unsure of it.
    if rule is None or ans is None:
        return False
    band = rule.get("band")
    if band is not None:
        noul = getattr(ans, "noul", None)
        return noul is not None and band[0] < noul < band[1]
    confidence = getattr(ans, "confidence", None)
    return confidence is not None and confidence < rule["below_confidence"]


def reduce(answers) -> str:
    """The verdict is computed here, in code — never asked of the model."""
${rules}
    return ${py(p.reduce.otherwise)}
${p.residual ? `\n# Still requires a generative model:\n${
  // Python's tokenizer ends a line at a lone \r as readily as at \n, so splitting on '\n'
  // alone leaves everything after a CR uncommented — and executed at import. Residual is
  // prose lifted from a human document and arrives with that document's line endings.
  p.residual.split(/\r\n|\r|\n/g).map(l => `# ${l}`).join('\n')}\n` : ''}`
}
