import type { EntryType, JsonValue } from '../contract.js'
import { uncertaintyOf } from '../ir.js'
import type { Decision, Program } from '../ir.js'

/**
 * A Python literal for an EntryType. JSON.stringify is not enough here: JSON's
 * true/false/null are not Python, and String(v) on an object renders
 * "[object Object]". JSON string escapes ARE a subset of Python's, so strings
 * pass through JSON.stringify unchanged.
 */
function py(v: JsonValue | undefined): string {
  if (v === undefined || v === null) return 'None'
  if (typeof v === 'string') return JSON.stringify(v)
  if (typeof v === 'boolean') return v ? 'True' : 'False'
  if (typeof v === 'number') return Number.isFinite(v) ? String(v) : 'None'
  if (Array.isArray(v)) return `[${v.map(py).join(', ')}]`
  return `{${Object.entries(v).map(([k, x]) => `${JSON.stringify(k)}: ${py(x)}`).join(', ')}}`
}

/**
 * A Python literal for a THRESHOLD, which py() alone cannot render. py() maps every
 * non-finite number to `None` because a JSON null really is None wherever an EntryType
 * appears — but in `_compare(answers, "q", ">=", None)` that is a TypeError the moment
 * the rule is evaluated, where runReducer's `2 >= NaN` is simply false. Python has the
 * literals: `float("inf") / float("-inf") / float("nan")` reproduce JS comparison
 * results exactly. validateProgram refuses most of these now (a noul or choice threshold
 * must be in 0..1, a score threshold inside level-index space), but NOT NaN against a
 * score — `NaN < 0` and `NaN > levels-1` are both false — so the emitter is the last
 * line for that one. Anything that is not a number at all still goes through py(), which
 * renders it faithfully rather than guessing.
 */
function pyThreshold(v: unknown): string {
  if (typeof v === 'number' && !Number.isFinite(v)) {
    return Number.isNaN(v) ? 'float("nan")' : v > 0 ? 'float("inf")' : 'float("-inf")'
  }
  return py(v as JsonValue)
}

function question(d: Decision): string {
  if (d.kind === 'noul') {
    const c = d.criteria && !Array.isArray(d.criteria)
      ? (d.criteria as { true?: EntryType; false?: EntryType }) : undefined
    // criteria is passed explicitly: the library's own default is unreachable dead code.
    const crit = c ? `, criteria=NoulCriteria(true=${py(c.true ?? null)}, false=${py(c.false ?? null)})` : ''
    return `    ${py(d.id)}: Noul(instructions=${py(d.instructions)}${crit}),`
  }
  if (d.kind === 'score') {
    const lv = (d.criteria as readonly EntryType[]).map(py).join(', ')
    return `    ${py(d.id)}: Score(instructions=${py(d.instructions)}, criteria=[${lv}]),`
  }
  const opts = Object.entries(d.criteria as Record<string, EntryType>)
    .map(([k, v]) => `${py(k)}: ${py(v)}`).join(', ')
  return `    ${py(d.id)}: Choice(instructions=${py(d.instructions)}, criteria={${opts}}),`
}

export function emitLangchain(p: Program, name = 'program'): string {
  // Each decision's uncertainty rule, RESOLVED from the Program (uncertaintyOf supplies
  // jevc's defaults where a decision declares none) rather than assumed to be 0.5.
  const uncertainties = p.decisions.map(d => {
    const u = uncertaintyOf(d)
    const body = 'band' in u
      ? `{"band": [${py(u.band[0])}, ${py(u.band[1])}]}`
      : `{"below_confidence": ${py(u.belowConfidence)}}`
    return `    ${py(d.id)}: ${body},`
  }).join('\n')

  const rules = p.reduce.rules.map(r => {
    const conds = r.when.map(c => {
      // _choice(), not a subscript: `answers["q"].choice` raises KeyError on an
      // unanswered question and AttributeError on an answer that is not a choice, where
      // runtime.choiceOf (runtime.ts:32-37) returns undefined and the rule simply does
      // not fire. This branch was the one operator in this emitter that still crashed
      // where its own _compare and _uncertain skip.
      if (c.op === 'is') return `_choice(answers, ${py(c.id)}) == ${py(c.value)}`
      if (c.op === 'uncertain') return `_uncertain(answers, ${py(c.id)})`
      // pyThreshold(), not interpolation: Infinity and NaN are JS globals and Python
      // NameErrors, and py()'s None would turn the comparison into a TypeError.
      return `_compare(answers, ${py(c.id)}, ${py(c.op === 'gte' ? '>=' : '<=')}, ${pyThreshold(c.value)})`
    }).join(' and ')
    // `when: []` is an empty conjunction and `[].every(...)` is true, so the rule fires
    // unconditionally — `True` is what that means here, and joining nothing produced the
    // unparseable `if :`.
    return `    if ${conds || 'True'}:\n        return ${py(r.then)}`
  }).join('\n')

  return `# Generated by jevc for langchain-typesafe.
# api_key and base_url come from the environment: TypeSafeClassifier sets
# extra="forbid", so a stray kwarg is a hard error.
from langchain_typesafe import Choice, Noul, NoulCriteria, Score, TypeSafeClassifier

${name}_questions = {
${p.decisions.map(question).join('\n')}
}

classifier = TypeSafeClassifier(questions=${name}_questions, model="jev-latest")

# Each decision's uncertainty rule as the Program declares it. A noul answer is
# {type, noul} with no .confidence field at all, so its band is tested on .noul; a choice
# or score answer carries a required .confidence, which its floor is tested against.
_UNCERTAINTY = {
${uncertainties}
}


def _value(answers, qid):
    """The number a threshold compares against, as jevc's own runtime picks it: a noul's
    value, a score's level index, otherwise a choice's confidence. A choice answer has
    neither .noul nor .score, and falling back to 0 there made every >= fail and every
    <= pass whatever the model said. Nested getattr with a None sentinel, not "or": a
    legitimate noul of 0.0 is falsy and would fall through."""
    ans = answers.get(qid)
    if ans is None:
        return None
    noul = getattr(ans, "noul", None)
    if noul is not None:
        return noul
    score = getattr(ans, "score", None)
    if score is not None:
        return score
    return getattr(ans, "confidence", None)


def _choice(answers, qid):
    """A choice answer's chosen label, or None — mirrors runtime.choiceOf. getattr with a
    default, not attribute access: an unanswered question and an answer of the wrong kind
    (a NoulAnswer has no .choice at all) both collapse to None, and None matches no
    option, so the rule does not fire. Neither is an error a generated module could
    report anywhere."""
    return getattr(answers.get(qid), "choice", None)


def _compare(answers, qid, op, threshold) -> bool:
    """A rule whose question was not answered does not fire, in either direction: absence
    of evidence is not evidence, and it is bouncer's rule for the same situation. An
    unanswered question read as 0 satisfies every upper bound, which turns "we never
    asked" into a confident no."""
    v = _value(answers, qid)
    if v is None:
        return False
    return v >= threshold if op == ">=" else v <= threshold


def _uncertain(answers, qid) -> bool:
    rule = _UNCERTAINTY.get(qid)
    ans = answers.get(qid)
    # No answer means nothing was measured, which is not the same as being unsure of it.
    if rule is None or ans is None:
        return False
    band = rule.get("band")
    if band is not None:
        noul = getattr(ans, "noul", None)
        return noul is not None and band[0] < noul < band[1]
    confidence = getattr(ans, "confidence", None)
    return confidence is not None and confidence < rule["below_confidence"]


def reduce(answers) -> str:
    """The verdict is computed here, in code — never asked of the model."""
${rules}
    return ${py(p.reduce.otherwise)}
${p.residual ? `\n# Still requires a generative model:\n${
  // Python's tokenizer ends a line at a lone \r as readily as at \n, so splitting on '\n'
  // alone leaves everything after a CR uncommented — and executed at import. Residual is
  // prose lifted from a human document and arrives with that document's line endings.
  // NUL is the other character the tokenizer will not accept: CPython refuses a NUL
  // anywhere in source text, comments included ("source code string cannot contain null
  // bytes"), so one of them makes the whole module unimportable. It is the one hole left
  // in this emitter — every other user string goes through py() -> JSON.stringify, which
  // escapes it. Fuzzed the rest of C0 through ast.parse: \0, \n and \r are the only three
  // that escape or break a `#` comment, and the split already covers the other two.
  p.residual.split(/\r\n|\r|\n/g).map(l => `# ${l.replace(/\0/g, '\\x00')}`).join('\n')}\n` : ''}`
}
