import type { EntryType, JsonValue } from '../contract.js'
import type { Decision, Program } from '../ir.js'

/**
 * A Python literal for an EntryType. JSON.stringify is not enough here: JSON's
 * true/false/null are not Python, and String(v) on an object renders
 * "[object Object]". JSON string escapes ARE a subset of Python's, so strings
 * pass through JSON.stringify unchanged.
 */
function py(v: JsonValue | undefined): string {
  if (v === undefined || v === null) return 'None'
  if (typeof v === 'string') return JSON.stringify(v)
  if (typeof v === 'boolean') return v ? 'True' : 'False'
  if (typeof v === 'number') return Number.isFinite(v) ? String(v) : 'None'
  if (Array.isArray(v)) return `[${v.map(py).join(', ')}]`
  return `{${Object.entries(v).map(([k, x]) => `${JSON.stringify(k)}: ${py(x)}`).join(', ')}}`
}

function question(d: Decision): string {
  if (d.kind === 'noul') {
    const c = d.criteria && !Array.isArray(d.criteria)
      ? (d.criteria as { true?: EntryType; false?: EntryType }) : undefined
    // criteria is passed explicitly: the library's own default is unreachable dead code.
    const crit = c ? `, criteria=NoulCriteria(true=${py(c.true ?? null)}, false=${py(c.false ?? null)})` : ''
    return `    ${py(d.id)}: Noul(instructions=${py(d.instructions)}${crit}),`
  }
  if (d.kind === 'score') {
    const lv = (d.criteria as readonly EntryType[]).map(py).join(', ')
    return `    ${py(d.id)}: Score(instructions=${py(d.instructions)}, criteria=[${lv}]),`
  }
  const opts = Object.entries(d.criteria as Record<string, EntryType>)
    .map(([k, v]) => `${py(k)}: ${py(v)}`).join(', ')
  return `    ${py(d.id)}: Choice(instructions=${py(d.instructions)}, criteria={${opts}}),`
}

export function emitLangchain(p: Program, name = 'program'): string {
  const rules = p.reduce.rules.map(r => {
    const conds = r.when.map(c => {
      if (c.op === 'is') return `answers[${py(c.id)}].choice == ${py(c.value)}`
      if (c.op === 'uncertain') return `answers[${py(c.id)}].confidence < 0.5`
      // A noul answer has .noul, a score answer has .score; neither has both. Nested
      // getattr, not `or`: a legitimate noul of 0.0 is falsy and would fall through.
      const read = `getattr(answers[${py(c.id)}], "noul", getattr(answers[${py(c.id)}], "score", 0))`
      return `(${read}) ${c.op === 'gte' ? '>=' : '<='} ${c.value}`
    }).join(' and ')
    return `    if ${conds}:\n        return ${py(r.then)}`
  }).join('\n')

  return `# Generated by jevc for langchain-typesafe.
# api_key and base_url come from the environment: TypeSafeClassifier sets
# extra="forbid", so a stray kwarg is a hard error.
from langchain_typesafe import Choice, Noul, NoulCriteria, Score, TypeSafeClassifier

${name}_questions = {
${p.decisions.map(question).join('\n')}
}

classifier = TypeSafeClassifier(questions=${name}_questions, model="jev-latest")


def reduce(answers) -> str:
    """The verdict is computed here, in code — never asked of the model."""
${rules}
    return ${py(p.reduce.otherwise)}
${p.residual ? `\n# Still requires a generative model:\n${p.residual.split('\n').map(l => `# ${l}`).join('\n')}\n` : ''}`
}
