import type { EntryType } from '../contract.js'
import type { Condition, Decision, Program } from '../ir.js'

// JSON.stringify is the escaper: it handles quotes, backslashes, newlines,
// unicode, and non-string EntryType values (objects/arrays) uniformly. A
// hand-rolled escaper is easy to get wrong in ways that only show up on
// inputs the fixtures don't cover (see fix-round-1 items 2-3).
const idKey = (id: string) => (/^[A-Za-z_$][\w$]*$/.test(id) ? id : JSON.stringify(id))

function provenance(d: Decision): string {
  if (!d.source) return ''
  // A `//` line comment can't contain a newline; source.quote might.
  const quote = d.source.quote.replace(/\r\n|\r|\n/g, ' ')
  return `  // from ${d.source.file}:${d.source.line} — "${quote}"\n`
}

function emitDecision(d: Decision): string {
  const head = `${provenance(d)}  ${idKey(d.id)}: `
  if (d.kind === 'noul') {
    const crit = d.criteria && !Array.isArray(d.criteria)
      ? `, criteria: ${JSON.stringify(d.criteria)}` : ''
    return `${head}{ type: 'noul', instructions: ${JSON.stringify(d.instructions)}${crit} },`
  }
  if (d.kind === 'score') {
    const levels = (d.criteria as readonly EntryType[]).map(c => JSON.stringify(c)).join(', ')
    // `as const` is load-bearing: without it ScoreOf<T> degrades to `number`.
    return `${head}{ type: 'score', instructions: ${JSON.stringify(d.instructions)}, criteria: [${levels}] as const },`
  }
  const entries = Object.entries(d.criteria as Record<string, EntryType>)
    .map(([k, v]) => `${idKey(k)}: ${JSON.stringify(v)}`).join(', ')
  return `${head}{ type: 'choice', instructions: ${JSON.stringify(d.instructions)}, criteria: { ${entries} } as const },`
}

function emitCondition(c: Condition): string {
  // Signatures must match runtime.isUncertain / runtime.choiceOf exactly (Task 6).
  if (c.op === 'uncertain') return `isUncertain(a, ${JSON.stringify(c.id)}, program)`
  // A cast (`a[id] as ChoiceAnswer`) would silence the discriminated-union
  // narrowing error exactly where the generated code is least inspectable;
  // a helper call keeps the emitted code cast-free, same shape as value()/isUncertain().
  if (c.op === 'is') return `choiceOf(a, ${JSON.stringify(c.id)}) === ${JSON.stringify(c.value)}`
  return `value(a, ${JSON.stringify(c.id)}) ${c.op === 'gte' ? '>=' : '<='} ${c.value}`
}

export function emitNative(p: Program, name = 'program'): string {
  const rules = p.reduce.rules
    .map(r => `  if (${r.when.map(emitCondition).join(' && ')}) return ${JSON.stringify(r.then)}`)
    .join('\n')

  return `// Generated by jevc. Review the questions and thresholds — they are the
// part humans must check. Regenerate with: jevc compile
import type { JevAnswer, Program } from 'jevc'
import { value, isUncertain, choiceOf } from 'jevc'

export const ${name}Questions = {
${p.decisions.map(emitDecision).join('\n')}
} as const

/** Carried so the reducer can resolve each decision's uncertainty rule. */
export const program = ${JSON.stringify({ decisions: p.decisions, reduce: p.reduce, residual: p.residual, dropped: p.dropped }, null, 2)} as unknown as Program

/** The verdict is computed here, in code — never asked of the model. */
export function reduce(a: Record<string, JevAnswer>): string {
${rules}
  return ${JSON.stringify(p.reduce.otherwise)}
}
${p.residual ? `\n/* Still requires a generative model:\n${p.residual}\n*/\n` : ''}`
}
