import type { Condition, Decision, Program } from '../ir.js'

const q = (s: string) => `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`
const idKey = (id: string) => (/^[A-Za-z_$][\w$]*$/.test(id) ? id : q(id))

function provenance(d: Decision): string {
  if (!d.source) return ''
  return `  // from ${d.source.file}:${d.source.line} — "${d.source.quote}"\n`
}

function emitDecision(d: Decision): string {
  const head = `${provenance(d)}  ${idKey(d.id)}: `
  if (d.kind === 'noul') {
    const crit = d.criteria && !Array.isArray(d.criteria)
      ? `, criteria: ${JSON.stringify(d.criteria)}` : ''
    return `${head}{ type: 'noul', instructions: ${q(d.instructions)}${crit} },`
  }
  if (d.kind === 'score') {
    const levels = (d.criteria as readonly string[]).map(c => q(String(c))).join(', ')
    // `as const` is load-bearing: without it ScoreOf<T> degrades to `number`.
    return `${head}{ type: 'score', instructions: ${q(d.instructions)}, criteria: [${levels}] as const },`
  }
  const entries = Object.entries(d.criteria as Record<string, unknown>)
    .map(([k, v]) => `${idKey(k)}: ${v == null ? 'null' : q(String(v))}`).join(', ')
  return `${head}{ type: 'choice', instructions: ${q(d.instructions)}, criteria: { ${entries} } as const },`
}

function emitCondition(c: Condition): string {
  // Signature must match runtime.isUncertain(answers, id, program) exactly.
  if (c.op === 'uncertain') return `isUncertain(a, ${q(c.id)}, program)`
  if (c.op === 'is') return `a[${q(c.id)}]?.choice === ${q(c.value)}`
  return `value(a, ${q(c.id)}) ${c.op === 'gte' ? '>=' : '<='} ${c.value}`
}

export function emitNative(p: Program, name = 'program'): string {
  const rules = p.reduce.rules
    .map(r => `  if (${r.when.map(emitCondition).join(' && ')}) return ${q(r.then)}`)
    .join('\n')

  return `// Generated by jevc. Review the questions and thresholds — they are the
// part humans must check. Regenerate with: jevc compile
import type { JevAnswer, Program } from 'jevc'
import { value, isUncertain } from 'jevc'

export const ${name}Questions = {
${p.decisions.map(emitDecision).join('\n')}
} as const

/** Carried so the reducer can resolve each decision's uncertainty rule. */
export const program = ${JSON.stringify({ decisions: p.decisions, reduce: p.reduce, residual: p.residual, dropped: p.dropped }, null, 2)} as unknown as Program

/** The verdict is computed here, in code — never asked of the model. */
export function reduce(a: Record<string, JevAnswer>): string {
${rules}
  return ${q(p.reduce.otherwise)}
}
${p.residual ? `\n/* Still requires a generative model:\n${p.residual}\n*/\n` : ''}`
}
